spring:
  application:
    name: appointment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: {MQ_HOST}
    port: {MQ_PORT}
    username: {MQ_USER}
    password: {MQ_PASSWORD}
user:
  service:
    url: ${USER_SERVICE_HOST}/users