spring:
  application:
    name: medication-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
api:
  user-service-host: ${USER_SERVICE_HOST}
  medical-record-service-host: ${MEDICAL_RECORD_SERVICE_HOST}
